### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by PhilterPaper** [avery-laird/breaker#1]
I am looking for a working example of Knuth-Plass in a language I can understand, in order to compare its algorithm against the Perl _Text::KnuthPlass_ implementation that I have taken over from Simon Cozens. It has a number of bugs that I need to fix before I can proceed with enhancements. It is derived from Bram Stein's _typeset_ package (Javascript), which itself evidently has a number of bugs (but unfortunately is unsupported).

Is _breaker_ a fresh implementation, or is it derived from _typeset_? I tried running `example.html`, but it doesn't seem to do any KP line breaking (just plain HTML). I see the HTML calls for `out/breaker.js`, but there doesn't seem to be any such file. I do see a `breaker.ts` -- how close is that to Javascript? I'm guessing it's a _typescript_ file, but I'm not familiar with the language.

Is _breaker_ still under active development, and how do I run the example(s)? Do I need to install something to get it to run? I'm using Windows 10. Thanks much for any information.

**Comment by avery-laird** [comment]
Sorry for the delay in getting back to you. Breaker is not derived from typeset, rather it's almost identical to the algorithm written by Knuth in his paper. I highly recommend taking a look, it's a terrific paper: http://www.eprg.org/G53DOC/pdfs/knuth-plass-breaking.pdf

To "compile" typescript into javascript, you will need the typescript compiler: https://www.typescriptlang.org/

Breaker isn't under active development anymore. The examples_should_ run, but it's been some time since I tested anything. Hope this helps.

**Comment by PhilterPaper** [comment]
Thanks for getting back to me on this. I tried the online ts compiler but it didn't seem to be happy with some stuff that needed to be included, If I want to actually _run_ this thing, I'll probably have to do a full installation. However, as it appears to be well-structured and documented, now that I understand what ts is, I should still be able pick apart the algorithm and see where the Perl code deviates. I'll try that first, and will re-open if I have further questions.
